---
title: "À propos de moi"
---

Je suis Clément et cette page présente mon univers : j'aime l'analyse de données et la programmation, mais aussi la cuisine et l'artisanat.

## Mon CV
J'ai un [CV en ligne](https://clement-lvd.github.io/CV) et un [CV en .pdf](https://github.com/Clement-LVD/CV/blob/main/CV_Clement_LVD.pdf).

## Projets perso de programmation
Je suis passionné d'analyses de données. Par exemple, en 2025, j'ai fait un package de R pour accompagner l'activité de programmation : [**codexplor**](https://clement-lvd.github.io/codexplor). C'est une aide précieuse pour révéler des faiblesses d'un projet de programmation, afin de les corriger au fur-et-à-mesure du développement. 

## Ma cuisine
J'essaye de cuisiner presque tous les jours. 

Voici quelques photos partagées sur Instagram de mon alimentation du quotidien, sans prétention.

<iframe src="https://www.instagram.com/dishes_and_crafts/embed" width="100%" height="600px"></iframe>

## Mes créations d'artisanat
La première fois que j'ai mis les mains dans le ciment, c'était en 2008. Voici quelques photos des 'chantiers' que j'ai au compteur :

[wip]

