---
title: "À propos de moi"
---

Je suis Clément et j'aime l'analyse de données et la programmation, mais aussi la cuisine et l'artisanat.

## Profils en ligne

```{r echo = F}

myself <- data.frame(Parcours = "[CV en .pdf](https://github.com/Clement-LVD/CV/blob/main/CV_Clement_LVD.pdf)"
           , Programmation = "[Repos github publics](https://github.com/Clement-LVD)"
           , Universitaire = "[Profil researchgate](https://www.researchgate.net/profile/Clement-Laverdet)"
           )

knitr::kable(t(myself))

```

## Projets github publics

```{r echo=F}
## Repos public github

repos <- readLines(warn = F, "https://api.github.com/users/Clement-LVD/repos")
repos <- jsonlite::fromJSON(repos)

links <- paste0( "[", repos$name, "](", repos$svn_url, ")" )
tablee <- data.frame(  repos = links, description = repos$description  )

tablee <- tablee[order(tablee$repos, decreasing = T),]

knitr::kable(tablee , row.names = F)
```


---

### Recherches universitaires

<iframe src="https://scanr.enseignementsup-recherche.gouv.fr/authors/idref258712619" width="100%" height="600px" 
sandbox="allow-scripts allow-same-origin"></iframe>

---

### Cuisine & créations
J'essaye de cuisiner presque tous les jours et je réalise divers objets, généralement en menuiserie. 

Voici des photos de mon alimentation du quotidien, sans prétention.

<iframe src="https://www.instagram.com/diners_quotidiens/embed" width="80%" height="600px"></iframe>
