name: Render README.qmd

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup R  
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'latest'

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render README.qmd
        run: |
          quarto render README.qmd --to gfm

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md
          git commit -m "Auto-update README.md from README.qmd" || echo "No changes to commit"
          git push
          
