name: Render README.qmd

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write  # Autorise les actions à pousser du code

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
         persist-credentials: true  # Important pour pousser des commits

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'latest'

      - name: Install R packages
        run: |
          Rscript -e 'install.packages(c("rmarkdown", "knitr", "jsonlite"), repos="https://cloud.r-project.org/")'

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render README.qmd
        run: |
          quarto render README.qmd --to gfm
          quarto render README.qmd --to html

      - name: Copy README.html to index.html
        run: cp README.html index.html

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md index.html
          git commit -m "Auto-update README.md and index.html from README.qmd" || echo "No changes to commit"
          git push
